### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by diogoalmeida** [smiranda/MetaPi#1]

**Comment by smiranda** [comment]
Which compiler did you try to use ?
Can you provide an error log ?

**Comment by diogoalmeida** [comment]
Hi Sebastiao,

Thanks for the quick reply. I used a gcc enriched terminal.

Thanks and best wishes,
Diogo

**Comment by smiranda** [comment]
Please provide me with the error log and compiler version (I'm assuming that by gcc you mean g++, and that you are using a c++11 compliant version)

**Comment by diogoalmeida** [comment]
But...

**Comment by smiranda** [comment]
Should compile now.
